const mongoose = require("mongoose");

module.exports = mongoose.model(
  "invDB",
  new mongoose.Schema({
    MemberID: String,
    DartRifle: Number,
    Shovel: Number,
    FishingRod: Number,
    Laptop: Number,
    TranquilizerDart: Number,
    Phone: Number,
    Fox: Number,
    Chicken: Number,
    Cow: Number,
    Dove: Number,
    Boar: Number,
    Panda: Number,
    Turkey: Number,
    Swan: Number,
    Duck: Number,
    Dodo: Number,
    Fish: Number,
    TropicalFish: Number,
    PufferFish: Number,
    Dolphin: Number,
    Seal: Number,
    Vaquita: Number,
    Shrimp: Number,
    Squid: Number,
    Octopus: Number,
    Lobster: Number,
    Bug: Number,
    Worm: Number,
    Cricket: Number,
    Beetle: Number,
    Fossil: Number,
    Treasure: Number,
    Garbage: Number,
    Banknote: Number,
  })
);
