const mongoose = require("mongoose");

module.exports = mongoose.model(
  "setupDB",
  new mongoose.Schema({
    GuildID: String,
    CommunityRoleID: String,
    StaffRoleID: String,
    AdminRoleID: String,
    LogChannelID: String,
    TicketParentID: String,
    TicketOpenedID: String,
    TicketLockedID: String,
    TicketMessageID: String,
    TicketChannelID: String,
    TicketTranscript: Boolean,
    TicketTranscriptID: String,
    VerificationMode: Boolean,
    VerificationChannelID: String,
    VerificationMessageID: String,
    LogChannelCreateSetup: Boolean,
    LogChannelDeleteSetup: Boolean,
    LogVCJoinSetup: Boolean,
    LogVCLeaveSetup: Boolean,
    LogChannelUpdateSetup: Boolean,
    LogBanSetup: Boolean,
    LogUnbanSetup: Boolean,
    LogKickUserSetup: Boolean,
    LogUpdateUserSetup: Boolean,
    LogInviteCreateSetup: Boolean,
    LogMessageDeleteSetup: Boolean,
    LogMessageUpdateSetup: Boolean,
    LogRoleCreateSetup: Boolean,
    LogRoleDeleteSetup: Boolean,
    LogRoleUpdateSetup: Boolean,
  })
);
