const mongoose = require("mongoose");

module.exports = mongoose.model(
  "setupDB",
  new mongoose.Schema({
    GuildID: String,
    CommunityRoleID: String,
    StaffRoleID: String,
    AdminRoleID: String,
    LogChannelID: String,
    TicketParentID: String,
    TicketOpenedID: String,
    TicketLockedID: String,
    TicketTranscriptID: String,
    JTCChannelID: String,
    JTCSettingID: String,
    JTCCategoryID: String,
    VerificationSetuped: Boolean,
    VerificationType: String,
    VerificationChannelID: String,
    VerificationCategoryID: String,
    VerificationMessageID: String,
    JTCInfo: Array,
    LogChannelCreateSetup: Boolean,
    LogChannelDeleteSetup: Boolean,
    LogVCJoinSetup: Boolean,
    LogVCLeaveSetup: Boolean,
    LogChannelUpdateSetup: Boolean,
    LogBanSetup: Boolean,
    LogUnbanSetup: Boolean,
    LogKickUserSetup: Boolean,
    LogUpdateUserSetup: Boolean,
    LogInviteCreateSetup: Boolean,
    LogMessageDeleteSetup: Boolean,
    LogMessageUpdateSetup: Boolean,
    LogRoleCreateSetup: Boolean,
    LogRoleDeleteSetup: Boolean,
    LogRoleUpdateSetup: Boolean,
    LogConfirmSetup: Boolean,
  })
);
